on:
  push:
    branches:
      - master
    paths:
      - 'package.json'
name: Deploy Extension
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5.0.0
      - name: Use Node.js Latest
        uses: actions/setup-node@v5.0.0
        with:
          node-version: 'latest'
      - run: npm install
      - name: Publish to Visual Studio Marketplace
        run: npx vsce publish -p ${{ secrets.VSCE_TOKEN }}
        env:
          VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}